### ISSUE TITLE
Find hotkey not working after video plays

### ISSUE THREAD

**Issue by Skillkiller** [AgileProggers/archiv-frontend#8]
The Ctrl + F hotkey no longer works on the entire website after watching a video. Nothing visible happens. I would expect the normal browser search dialog to open or the focus to switch to the search. In the browser console I get the following error:
![grafik](https://user-images.githubusercontent.com/18444809/163734319-b3106d15-549e-41ee-84d4-02794534f7d8.png)

Steps to reproduce the error:
1. open any video
2. go to another page via the menu
3. press Ctrl + F

**Comment by d-delaey** [comment]
@Skillkiller Fixed in #6
